[package]
name = "tket-json-rs"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.60"

readme = "README.md"
documentation = "https://docs.rs/tket-json-rs/"
repository = "https://github.com/CQCL/tket-json-rs"

description = "Serializable definition of TKET circuits and operations."
keywords = ["tket", "quantinuum", "quantum"]
categories = ["compilers"]

[lib]
name = "tket_json_rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.4", features = ["serde"] }
pyo3 = { version = "0.19.0", optional = true }
pythonize ={version = "0.19.0", optional = true}


[features]
pyo3 = ["dep:pyo3", "dep:pythonize", "tket2ops"]
tket2ops = []