name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types: [checks_requested]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "--cfg=ci_run"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Build docs
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: "-Dwarnings"

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
        # workaround to ignore non-stable tests when running the merge queue checks
        # see: https://github.community/t/how-to-conditionally-include-exclude-items-in-matrix-eg-based-on-branch/16853/6
        isMerge:
            - ${{ github.event_name == 'merge_group' }}
        exclude:
          - rust: beta
            isMerge: true
    name: tests (Rust ${{ matrix.rust }})
    steps:
      - uses: actions/checkout@v5
      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Configure default rust toolchain
        run: rustup override set ${{steps.toolchain.outputs.name}}
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-rust-${{ matrix.rust }}
      - name: Build with no features
        run: cargo build --verbose --no-default-features
      - name: Build with all features
        run: cargo build --verbose --all-features
      - name: Tests with no features
        run: cargo test --verbose --no-default-features
      - name: Tests with all features
        run: cargo test --verbose --all-features


  # Run tests on the minimum supported rust version, with minimal dependency versions
  tests-msrv:
    if: ${{ github.event_name != 'merge_group' }}
    runs-on: ubuntu-latest
    name: tests (Rust MSRV, min dependencies)
    steps:
      - uses: actions/checkout@v5
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install MSRV toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.75"
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          # Nightly must be installed for `cargo-minimal-versions` to work
          toolchain: "nightly"
      - name: Configure default rust toolchain
        run: rustup override set ${{steps.toolchain.outputs.name}}
      - uses: cargo-bins/cargo-binstall@main
      - name: Install cargo-minimal-versions
        run: |
          cargo binstall cargo-hack --force
          cargo binstall cargo-minimal-versions --force
      - name: Pin transitive dependencies not compatible with our MSRV
        # Add new dependencies as needed if the check fails due to
        # "package `XXX` cannot be built because it requires rustc YYY or newer, while the currently active rustc version is 1.75.0"
        run: |
          rm Cargo.lock
          cargo add -p tket-json-rs toml_datetime@=0.7.1
          cargo add -p tket-json-rs toml_parser@=1.0.2
      - name: Build with no features
        run: cargo minimal-versions --direct test --verbose  --no-default-features --no-run
      - name: Tests with no features
        run: cargo minimal-versions --direct test --verbose  --no-default-features
      - name: Build with all features
        run: cargo minimal-versions --direct test --verbose  --all-features --no-run
      - name: Tests with all features
        run: cargo minimal-versions --direct test --verbose  --all-features
