name: Rust Semver Checks
on:
  pull_request_target:
    branches:
      - main

jobs:
  rs-semver-checks:
    uses: CQCL/hugrverse-actions/.github/workflows/rs-semver-checks.yml@main
    with:
      apt-dependencies: capnproto
    secrets:
      GITHUB_PAT: ${{ secrets.HUGRBOT_PAT }}
